import json
import os


__all__ = (
    'BLOG_POST_DOCUMENT_NAME',
    'SITE_USER_DOCUMENT_NAME',
    'FARM_ANIMAL_DOCUMENT_NAME',
    'ELASTICSEARCH_CONNECTION',
    'ADDRESS_COUNTRY_DOCUMENT_NAME',
    'ADDRESS_CITY_DOCUMENT_NAME',
    'ADDRESS_ADDRESS_DOCUMENT_NAME',
)

ELASTICSEARCH_CONNECTION_DEFAULTS = {
    'hosts': ['localhost'],
    'timeout': 5,
}

ELASTICSEARCH_CONNECTION = os.environ.get(
    "ELASTICSEARCH_CONNECTION",
    ELASTICSEARCH_CONNECTION_DEFAULTS
)

if isinstance(ELASTICSEARCH_CONNECTION, str):
    try:
        ELASTICSEARCH_CONNECTION = json.loads(ELASTICSEARCH_CONNECTION)
    except:
        ELASTICSEARCH_CONNECTION = ELASTICSEARCH_CONNECTION_DEFAULTS


BLOG_POST_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_BLOG_POST_DOCUMENT_NAME",
    "blog_post"
)

SITE_USER_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_SITE_USER_DOCUMENT_NAME",
    "site_user"
)


FARM_ANIMAL_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_FARM_ANIMAL_DOCUMENT_NAME",
    "farm_animal"
)

ADDRESS_COUNTRY_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_ADDRESS_COUNTRY_DOCUMENT_NAME",
    "address_country"
)

ADDRESS_CITY_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_ADDRESS_CITY_DOCUMENT_NAME",
    "address_city"
)

ADDRESS_ADDRESS_DOCUMENT_NAME = os.environ.get(
    "GRAPHENE_ELASTIC_EXAMPLE_ADDRESS_ADDRESS_DOCUMENT_NAME",
    "address_address"
)
