name: test

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        es-version: ['6', '7']
        include:
        - python-version: '3.6'
          tox_env: py36-elastic6
          requirements: django_2_2
        - python-version: '3.6'
          tox_env: py36-elastic7
          requirements: django_3_1

        - python-version: '3.7'
          tox_env: py37-elastic6
          requirements: django_2_2
        - python-version: '3.7'
          tox_env: py37-elastic7
          requirements: django_3_1

        - python-version: '3.8'
          tox_env: py38-elastic6
          requirements: django_2_2
        - python-version: '3.8'
          tox_env: py38-elastic7
          requirements: django_3_1

        - python-version: '3.9'
          tox_env: py39-elastic6
          requirements: django_2_2
        - python-version: '3.9'
          tox_env: py39-elastic7
          requirements: django_3_1

        - python-version: '3.10'
          tox_env: py310-elastic6
          requirements: django_2_2
        - python-version: '3.10'
          tox_env: py310-elastic7
          requirements: django_3_1

    services:
      elasticsearch:
        image: bitnami/elasticsearch:${{ matrix.es-version }}
        ports:
          - 9200:9200
        options: >-
          -e="discovery.type=single-node"
          --health-cmd="curl http://localhost:9200/_cluster/health"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pip-tools
        python -m pip install tox
        pip-compile examples/requirements/${{ matrix.requirements }}.in
        pip-compile examples/requirements/elastic_${{ matrix.es-version }}x.in
        pip-compile examples/requirements/test.in
        python -m pip install -r examples/requirements/${{ matrix.requirements }}.txt
        python -m pip install -r examples/requirements/elastic_${{ matrix.es-version }}x.txt
        python -m pip install -r examples/requirements/test.txt
    - name: Run tests
      uses: nick-invision/retry@v2
      with:
        command: tox -e ${{ matrix.tox_env }} -- --color yes
        timeout_minutes: 15
        max_attempts: 3
    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Run Tests

  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
        debug: True
